name: learn-github-actions
on:
  push:
    branches:
      - dev
env:
  TINGTONG: ${{ secrets.TINGTONG }}

jobs:
  khela_suru:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Run Build
        run: npm run build

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print tingtong
        run: echo "$Greeting $First_Name. Today is $TINGTONG!. Our current branch is ${{ steps.extract_branch.outputs.branch }}"
        env:
          First_Name: Naieem

      - name: Run test file
        run: npm run test-workflow
